### ISSUE TITLE
Is this repo still updated ?

### ISSUE THREAD

**Issue by KnifeOnlyI** [adisreyaj/angular-remix-icon#13]
I've checked to use the icon `sort-alphabet-asc` (added in remix-icon v3.7.0 at 2023-12-10) with angular-remix-icon with version 5.0.0 of `angular-remix-icon` but the icon is not available.

I see the last update of this repo is from 9 months ago. Can I create a pull requests to add icons ?

**Comment by adisreyaj** [comment]
Updated to latest version of remixicon.
