### ISSUE TITLE
No exported member error when i serve my project based on ANgular 10 

### ISSUE THREAD

**Issue by Rayen-cherni** [adisreyaj/angular-remix-icon#5]
ERROR in node_modules/angular-remix-icon/lib/angular-remix-icon.component.d.ts:12:21 - error TS2694: Namespace '"/home/rayen/Desktop/Relead/my-new-app/node_modules/@angular/core/core"' has no exported member 'ɵɵFactoryDeclaration'.

12     static ɵfac: i0.ɵɵFactoryDeclaration<AngularRemixIconComponent, never>;
                       ~~~~~~~~~~~~~~~~~~~~
node_modules/angular-remix-icon/lib/angular-remix-icon.component.d.ts:13:21 - error TS2694: Namespace '"/home/rayen/Desktop/Relead/my-new-app/node_modules/@angular/core/core"' has no exported member 'ɵɵComponentDeclaration'.

13     static ɵcmp: i0.ɵɵComponentDeclaration<AngularRemixIconComponent, "rmx-icon", never, { "name": "name"; }, {}, never, ["*"]>;
                       ~~~~~~~~~~~~~~~~~~~~~~
node_modules/angular-remix-icon/lib/angular-remix-icon.module.d.ts:11:21 - error TS2694: Namespace '"/home/rayen/Desktop/Relead/my-new-app/node_modules/@angular/core/core"' has no exported member 'ɵɵFactoryDeclaration'.

11     static ɵfac: i0.ɵɵFactoryDeclaration<RemixIconModule, [{ optional: true; }]>;
                       ~~~~~~~~~~~~~~~~~~~~
node_modules/angular-remix-icon/lib/angular-remix-icon.module.d.ts:12:21 - error TS2694: Namespace '"/home/rayen/Desktop/Relead/my-new-app/node_modules/@angular/core/core"' has no exported member 'ɵɵNgModuleDeclaration'.

12     static ɵmod: i0.ɵɵNgModuleDeclaration<RemixIconModule, [typeof i1.AngularRemixIconComponent], never, [typeof i1.AngularRemixIconComponent]>;
                       ~~~~~~~~~~~~~~~~~~~~~
node_modules/angular-remix-icon/lib/angular-remix-icon.module.d.ts:13:21 - error TS2694: Namespace '"/home/rayen/Desktop/Relead/my-new-app/node_modules/@angular/core/core"' has no exported member 'ɵɵInjectorDeclaration'.

13     static ɵinj: i0.ɵɵInjectorDeclaration<RemixIconModule>;

**Comment by adisreyaj** [comment]
Could you add the version of `angular` and `angular-remix-icon` that you are using?
