### ISSUE TITLE
Property name should be strong typed (each name of possible icons)

### ISSUE THREAD

**Issue by BarkhatovN** [adisreyaj/angular-remix-icon#9]

**Comment by adisreyaj** [comment]
Yeah...this would be a great addition. Will try to investigate a bit.

**Comment by smlshn** [comment]
This was not a good idea IMHO. 
Having strong typed names prevents you to interpolate icon name, which is needed picking up the icon based on some conditions. Also this makes using new icons impossible, the new one must be defined as a new type.

This just brings up a restriction which helps you to use correct icon names. What if I don't? I wont see the icon, that is all. I can fix it easily by double checking the icon name. 

But now I need to use some icons which their types are not defined in the lib. Now I need to open a PR an waiting it to get merged. 

Double check the name or opening a PR? which one?
